############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Resume"
url = "/resume"
weight = 3

[[main]]
name = "Blog"
url = "/blog"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Resume"
url = "/resume"
weight = 2

[[footer]]
name = "Blog"
url = "/blog"
weight = 3
